module.exports = {
  keyStages: ["Foundation Stage", "KS1", "KS2", "KS3", "KS4", "KS5"],
  examBoards: ["EdExcel", "AQA", "CCEA", "CIE", "ICAAE", "OCR", "WJEC", "SQA"],
  territories: [
    "England",
    "Guernsey",
    "Jersey",
    "Isle of Man",
    "Northern Ireland",
    "Scotland",
    "Wales",
  ],
  instituteLevels: [
    "Nursery",
    "First",
    "Primary",
    "Infant",
    "Junior",
    "Middle",
    "Secondary",
    "High",
    "All-through",
    "Post-16",
    "Other",
  ],
  instituteTypes: [
    "Academy",
    "College",
    "Free School",
    "Independent",
    "LA Maintained",
    "Special School",
    "Welsh School",
    "State FE",
    "Independent Fe",
    "6th Form",
    "General FE",
    "Land College",
    "Adult Learning / Council-run Services",
    "Art, Design and Performing Arts College",
    "Other",
  ],
  titles: ["Mr", "Mrs", "Miss", "Ms", "Mx", "Dr", "Sr"],
  roles: ["super-admin", "institute-admin", "teacher"],
};
